# Aufgaben Teil 3

Tipp: In der Menuleiste mit "Edit > Clear all Outputs" kannst du ein bisschen Übersicht schaffen, wenn viele Daten angezeigt werden.

## Pandas, again

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set(font_scale=1.2, style="whitegrid", palette='magma')
import matplotlib.pyplot as plt

In [ ]:
mpg = sns.load_dataset('mpg')
mpg.head(10)

### Gruppierungen

Mit pandas kann man Daten Gruppieren und so Werte über bestimmte ähnliche Zeilen berechnen.

In [ ]:
mpg_cyl = mpg.groupby('cylinders')
mpg_cyl.first() # Gibt pro Gruppe den ersten Wert aus

In [ ]:
# Man kann über gruppen iterieren
for name, group in mpg_cyl:
  print(name)
  print(group.shape)

In [ ]:
mpg_cyl_year = mpg.groupby(['cylinders', 'model_year']) # Kann auch nach mehreren Spalten gruppieren
mpg_cyl_year.first().head(10)

### Aufgaben

Bemerkung: `mpg` steht für den Verbrauch in "miles per gallon", höher ist besser. Werte in imperischen Einheiten, also pounds, gallons miles und cubic inches.

3.1. Verschaffe dir ein Bild des mpg-Datensets ähnlich "Tasks Part 2 Pandas". Das muss nicht gründlich sein.

3.2. Berechne den Durschnitt von `mpg` pro Anzahl Zylinder.

3.3. Erstelle eine Kopie des Dataframes, welches das Gewicht in kg anstatt lb hat. Tipp: 1 lb = 0.453 kg. Tipp 2: `dataframe['column'] = other_df['column']`. Tipp 3: `dataframe['column'] - 10` ist gültiger Code, probiere es mal aus.

3.4. Teile `mpg` in zwei Dataframes auf, eines mit der Spalte mpg und ein anderes mit allen anderen Spalten.

3.5. Verwende `groupby` und `for .. in ..` um folgendes zu berechnen: Was ist der Name des Autos mit dem höchsten Gewicht pro Jahr?

(Bonus 3.5.' Aufgabe 3.5. könnte man auch ohne `for .. in ..` lösen. Wie?)

3.6.a) Finde alle Zeilen mit NaN in `horsepower`

3.6.b) Berechne die durchschnittlichen `horspower` pro Anzahl Zylinder.

3.6.c) Erstelle eine Methode, die ein Dataframe nimmt und ein Dataframe zurückgibt, in welchem alle NaN-Werte in `horsepower` mit den Durschnittlichen `horspower` gruppiert nach Anzahl Zylinder ersetzt wurden. Tipp: Verwende die vorherigen Teilaufgaben und ein `for .. in ..` auf die Zeilen mit NaN. Es ist einfacher, nicht `fillna` zu verwenden, sondern das pro Zeile einzeln zu ersetzen.

In [ ]:
# 3.1
mpg.columns

In [ ]:
# 3.2
mpg_mean_by_cylinders = mpg.groupby('cylinders')['mpg'].mean()
print(mpg_mean_by_cylinders)

In [ ]:
# 3.3

mpg_copy = mpg.copy()
mpg_copy["weight_kg"] = mpg_copy["weight"] * 0.453

mpg_copy[["weight_kg", "weight"]]

In [ ]:
# 3.4
#  Teile mpg in zwei Dataframes auf, eines mit der Spalte mpg und ein anderes mit allen anderen Spalten.

mpg_mpg = mpg["mpg"].copy()
mpg_exc_mpg = mpg.drop(columns="mpg").copy()

print(mpg_mpg)
print(mpg_exc_mpg)

In [ ]:
# 3.5
max_weight_by_year_bonus = mpg.loc[mpg.groupby('model_year')['weight'].idxmax(), ['model_year', 'name', 'weight']]

In [24]:
# 3.6.a
rows_with_nan_horsepower = mpg[mpg['horsepower'].isna()]
rows_with_nan_horsepower

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl

In [ ]:
# 3.6.b
mean_horsepower_by_cylinders = mpg.groupby('cylinders')['horsepower'].mean()
mean_horsepower_by_cylinders

In [ ]:
# 3.6.c
def replace_nan_horsepower(df):
    # Calculate mean horsepower per cylinder group
    horsepower_means = df.groupby('cylinders')['horsepower'].mean()

    # Loop through rows with NaN and replace with the mean
    for idx, row in df[df['horsepower'].isna()].iterrows():
        cylinder_group = row['cylinders']
        df.at[idx, 'horsepower'] = horsepower_means[cylinder_group]

    return df